### PR TITLE
Update labels when synchronizing

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
When syncronizing a PR, labels are not getting updated according to the files the PR edits. This should fix that.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Pushed a second version that should be nicer because it only edits labels once.

**Comment by deivid-rodriguez** [comment]
@bronzdoc Could you have a look?

**Comment by deivid-rodriguez** [comment]
To give an example of what this PR is fixing. In https://github.com/rubygems/rubygems/pull/3807, I started changing only files in `bundler`, so that PR got labeled with `Bundler`. However, then I changed it to also modify files in `rubygems`. The PR should've been updated to also be labeled with `Rubygems`. That's what this PR is fixing.

**Review by bronzdoc — APPROVED** [review]
Thanks David!

**Comment by bronzdoc** [comment]
Will deploy this like in 20 mins

**Comment by deivid-rodriguez** [comment]
Awesome, thanks so much!

**Comment by bronzdoc** [comment]
@deivid-rodriguez done, let me know if you find any issue

**Comment by deivid-rodriguez** [comment]
It sounds like it didn't work. I just force-pushed https://github.com/rubygems/rubygems/pull/3792, and I would've expected the `Rubygems` label to have been added to it. So there's probably some bug in my implementation. Let's wait and see if it works for other PRs.

**Comment by bronzdoc** [comment]
hmm weird, I'll debug it tonight if you haven't found the problem by then

**Comment by deivid-rodriguez** [comment]
Thanks!

**Pull request merged**
